Java python crash cases (#1)
* chore: structure is changed and java is implemented

* chore: py is implemented

* chore: OutOfMemory is implemented

* chore: InternalErr is implemented

* chore: StackOverflow is implemented

* chore: Unknown error is implemented

* chore: Assertion error is implemented

* chore: bootstrap method error is implemented

* chore: class circularity error is implemented

* chore: class format error is implemented

* chore: unsupported class version error is implemented

* chore: exception in initializer error is implemented

* chore: incompatible class change error is implemented

* refactor: error message

* chore: illegal access error is implemented

* chore: instantiation error is implemented

* chore: no such field error is implemented

* fix: IllagalAccessError typo is fixed

* chore: no class def found error is implemented

* chore: unsatisfied link error is implemented

* refactor: temp errors are moved

* refactor: InternalErr renamed to Internal

* chore: unnecessary javas are removed and NameError.py is implemented

* chore: TypeError.py is implemented

* chore: IndexError.py is implemented

* chore: KeyError.py is implemented

* chore: ValueError.py is implemented

* chore: ZeroDivisionError.py is implemented

* chore: AttributeError.py is implemented

* chore: FileNotFoundError.py is implemented

* chore: UnboundLocalError.py is implemented

* chore: SyntaxError.py is implemented

* chore: IndentationError.py is implemented

* chore: RuntimeError.py is implemented

* chore: KeyboardInterrupt.py is implemented

* chore: OSError.py is implemented

* chore: SystemError.py is implemented

* chore: RecursionError.py is happened

* chore: mostly python errors are implemented

* chore: files are structured

* chore: c is implemented

* chore: oops kmod is removed

* chore: java nixes are ready

* refactor: file names are changed

* chore: files are renamed

* chore: nix is implemented

* chore: py is done

* chore: java nix is ready

* chore: c is ready

* chore: modules are ready

* chore: updated inputs

* chore: modules are ready 2

* fix: java and c are fixed

* chore: arguments are fixed

* fix: lower case issue is fixed in java module

* fix: lower case issue is fixed in java module

* refactor: service name is changed

* refactor: files are read from dirs

* chore: c is ready

* fix: module c is fixed

* chore: aarch64-linux is added

* feat: readme is ready

* refactor: readme is refactored

* refactor: prefixes are updated

* refactor: module prefix is edited

* refactor: readme is enhanced

* refactor: prefix reminder is enhanced